-- units.id 改為資料庫自動配號（GENERATED BY DEFAULT AS IDENTITY）
-- 背景：後台「新增系所」已改為不手動帶 id（見 app/api/admin/units/route.ts），
--       但既有 schema 的 units.id 仍是純 bigint，沒有預設值 → 不帶 id 會插入失敗。
-- 此 migration 補上 identity，並把序列指標推進到目前最大 id 之後，避免與既有 1~42 撞號。
-- 可重複執行（已是 identity 時跳過 ALTER）。
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='units'
      AND column_name='id' AND is_identity='YES') THEN
    EXECUTE 'ALTER TABLE public.units ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY';
  END IF;
END $$;
SELECT setval(pg_get_serial_sequence('public.units','id'),
  GREATEST((SELECT COALESCE(max(id),0) FROM public.units),1),
  (SELECT count(*)>0 FROM public.units));
