// 國家/地區清單（來源：教育部「大學校院校務資料庫」國別代碼）
// 由 scripts/gen_countries.py 從 docx 產生；填報「國家/地區」下拉以此為準。
export type Country = { code: string; zh: string; en: string; continent: string };

export const COUNTRIES: Country[] = [
  { code: "0", zh: "中華民國", en: "R.O.C", continent: "亞洲" },
  { code: "A00", zh: "大陸地區", en: "Mainland China", continent: "亞洲" },
  { code: "1", zh: "阿富汗", en: "Afghanistan", continent: "亞洲" },
  { code: "2", zh: "巴林", en: "Bahrain", continent: "亞洲" },
  { code: "3", zh: "孟加拉", en: "Bangladesh", continent: "亞洲" },
  { code: "4", zh: "不丹", en: "Bhutan", continent: "亞洲" },
  { code: "5", zh: "緬甸", en: "Myanmar", continent: "亞洲" },
  { code: "6", zh: "柬埔寨", en: "Cambodia", continent: "亞洲" },
  { code: "7", zh: "賽普勒斯", en: "Cyprus", continent: "亞洲" },
  { code: "8", zh: "印度", en: "India", continent: "亞洲" },
  { code: "9", zh: "印尼", en: "Indonesia", continent: "亞洲" },
  { code: "10", zh: "伊朗", en: "Iran", continent: "亞洲" },
  { code: "11", zh: "伊拉克", en: "Iraq", continent: "亞洲" },
  { code: "12", zh: "以色列", en: "Israel", continent: "亞洲" },
  { code: "13", zh: "日本", en: "JAPAN", continent: "亞洲" },
  { code: "14", zh: "約旦", en: "Jordan", continent: "亞洲" },
  { code: "15", zh: "南韓", en: "ROK", continent: "亞洲" },
  { code: "16", zh: "科威特", en: "Kuwait", continent: "亞洲" },
  { code: "17", zh: "寮國", en: "Laos", continent: "亞洲" },
  { code: "18", zh: "黎巴嫩", en: "Lebanon", continent: "亞洲" },
  { code: "19", zh: "馬來西亞", en: "Malaysia", continent: "亞洲" },
  { code: "20", zh: "馬爾地夫", en: "Maldives", continent: "亞洲" },
  { code: "21", zh: "尼泊爾", en: "Nepal", continent: "亞洲" },
  { code: "22", zh: "阿曼", en: "Oman", continent: "亞洲" },
  { code: "23", zh: "巴基斯坦", en: "Pakistan", continent: "亞洲" },
  { code: "24", zh: "菲律賓", en: "Philippines", continent: "亞洲" },
  { code: "25", zh: "卡達", en: "Qatar", continent: "亞洲" },
  { code: "26", zh: "沙烏地阿拉伯", en: "Saudi Arabia", continent: "亞洲" },
  { code: "27", zh: "新加坡", en: "Singapore", continent: "亞洲" },
  { code: "28", zh: "斯里蘭卡", en: "Sri Lanka", continent: "亞洲" },
  { code: "29", zh: "敘利亞", en: "Syria", continent: "亞洲" },
  { code: "30", zh: "泰國", en: "Thailand", continent: "亞洲" },
  { code: "31", zh: "土耳其", en: "Republic of Türkiye", continent: "亞洲" },
  { code: "32", zh: "阿拉伯聯合大公國", en: "United Arab Emirates", continent: "亞洲" },
  { code: "33", zh: "越南", en: "Vietnam", continent: "亞洲" },
  { code: "35", zh: "葉門", en: "Yemen", continent: "亞洲" },
  { code: "36", zh: "東帝汶", en: "East Timor", continent: "亞洲" },
  { code: "41", zh: "紐埃", en: "Niue", continent: "亞洲" },
  { code: "50", zh: "汶萊", en: "Brunei", continent: "亞洲" },
  { code: "60", zh: "香港", en: "Hong Kong", continent: "亞洲" },
  { code: "70", zh: "澳門", en: "Macao", continent: "亞洲" },
  { code: "71", zh: "巴勒斯坦", en: "Palestine", continent: "亞洲" },
  { code: "72", zh: "蒙古", en: "Mongolia", continent: "亞洲" },
  { code: "73", zh: "俄羅斯", en: "Russia", continent: "亞洲" },
  { code: "74", zh: "喬治亞", en: "Georgia", continent: "亞洲" },
  { code: "75", zh: "哈薩克", en: "Kazakhstan", continent: "亞洲" },
  { code: "76", zh: "吉爾吉斯", en: "Kyrgyzstan", continent: "亞洲" },
  { code: "77", zh: "烏茲別克", en: "Uzbekistan", continent: "亞洲" },
  { code: "78", zh: "亞美尼亞", en: "Armenia", continent: "亞洲" },
  { code: "79", zh: "塔吉克", en: "Tajikistan", continent: "亞洲" },
  { code: "80", zh: "土庫曼", en: "Turkmenistan", continent: "亞洲" },
  { code: "81", zh: "亞塞拜然", en: "Azerbaijan", continent: "亞洲" },
  { code: "82", zh: "摩爾多瓦", en: "Moldova", continent: "亞洲" },
  { code: "84", zh: "北韓", en: "DPRK", continent: "亞洲" },
  { code: "101", zh: "澳大利亞", en: "Australia", continent: "大洋洲" },
  { code: "102", zh: "斐濟", en: "Fiji", continent: "大洋洲" },
  { code: "103", zh: "諾魯", en: "Nauru", continent: "大洋洲" },
  { code: "104", zh: "紐西蘭", en: "New Zealand", continent: "大洋洲" },
  { code: "105", zh: "巴布亞紐幾內亞", en: "Papua New Guinea", continent: "大洋洲" },
  { code: "106", zh: "東加", en: "Tonga", continent: "大洋洲" },
  { code: "110", zh: "萬那杜", en: "Vanuatu", continent: "大洋洲" },
  { code: "111", zh: "索羅門群島", en: "Solomon Islands", continent: "大洋洲" },
  { code: "112", zh: "帛琉", en: "Palau", continent: "大洋洲" },
  { code: "113", zh: "馬紹爾群島共和國", en: "Marshall Islands", continent: "大洋洲" },
  { code: "115", zh: "吐瓦魯", en: "Tuvalu", continent: "大洋洲" },
  { code: "116", zh: "薩摩亞", en: "Samoa", continent: "大洋洲" },
  { code: "117", zh: "密克羅尼西亞", en: "Micronesia", continent: "大洋洲" },
  { code: "121", zh: "吉里巴斯", en: "Kiribati", continent: "大洋洲" },
  { code: "201", zh: "阿爾及利亞", en: "Algeria", continent: "非洲" },
  { code: "202", zh: "安哥拉", en: "Angola", continent: "非洲" },
  { code: "203", zh: "貝南", en: "Benin", continent: "非洲" },
  { code: "204", zh: "波札那", en: "Botswana", continent: "非洲" },
  { code: "205", zh: "蒲隆地", en: "Burundi", continent: "非洲" },
  { code: "206", zh: "喀麥隆", en: "Cameroon", continent: "非洲" },
  { code: "207", zh: "維德角", en: "Cape Verde", continent: "非洲" },
  { code: "208", zh: "中非", en: "Central African Republic", continent: "非洲" },
  { code: "209", zh: "查德", en: "Chad", continent: "非洲" },
  { code: "210", zh: "葛摩聯盟", en: "Comoros, Union of the", continent: "非洲" },
  { code: "211", zh: "剛果", en: "Congo, Republic of the", continent: "非洲" },
  { code: "212", zh: "吉布地", en: "Djibouti", continent: "非洲" },
  { code: "213", zh: "埃及", en: "Egypt", continent: "非洲" },
  { code: "214", zh: "赤道幾內亞", en: "Equatorial Guinea", continent: "非洲" },
  { code: "215", zh: "衣索比亞", en: "Ethiopia", continent: "非洲" },
  { code: "216", zh: "加彭", en: "Gabon", continent: "非洲" },
  { code: "217", zh: "甘比亞", en: "The Gambia", continent: "非洲" },
  { code: "218", zh: "迦納", en: "Ghana", continent: "非洲" },
  { code: "219", zh: "幾內亞", en: "Guinea", continent: "非洲" },
  { code: "220", zh: "幾內亞比索", en: "Guinea-Bissau", continent: "非洲" },
  { code: "221", zh: "象牙海岸", en: "Cote d'Ivoire", continent: "非洲" },
  { code: "222", zh: "肯亞", en: "Kenya", continent: "非洲" },
  { code: "223", zh: "賴索托", en: "Lesotho", continent: "非洲" },
  { code: "224", zh: "賴比瑞亞", en: "Liberia", continent: "非洲" },
  { code: "225", zh: "利比亞", en: "Libya", continent: "非洲" },
  { code: "226", zh: "馬達加斯加", en: "Madagascar", continent: "非洲" },
  { code: "227", zh: "馬拉威", en: "Malawi", continent: "非洲" },
  { code: "228", zh: "馬利", en: "Mali", continent: "非洲" },
  { code: "229", zh: "茅利塔尼亞", en: "Mauritania, Islamic Republic of", continent: "非洲" },
  { code: "230", zh: "模里西斯", en: "Mauritius", continent: "非洲" },
  { code: "231", zh: "摩洛哥", en: "Morocco", continent: "非洲" },
  { code: "232", zh: "莫三比克", en: "Mozambique", continent: "非洲" },
  { code: "233", zh: "尼日", en: "Niger", continent: "非洲" },
  { code: "234", zh: "奈及利亞", en: "Nigeria", continent: "非洲" },
  { code: "235", zh: "盧安達", en: "Rwanda", continent: "非洲" },
  { code: "236", zh: "聖多美普林西比", en: "Sao Tome and Principe", continent: "非洲" },
  { code: "237", zh: "塞內加爾", en: "Senegal", continent: "非洲" },
  { code: "238", zh: "塞席爾", en: "Seychelles", continent: "非洲" },
  { code: "239", zh: "獅子山共和國", en: "Sierra Leone", continent: "非洲" },
  { code: "240", zh: "索馬利亞民主共和國", en: "Somali Democratic Republic", continent: "非洲" },
  { code: "241", zh: "南非", en: "South Africa", continent: "非洲" },
  { code: "242", zh: "蘇丹", en: "Sudan", continent: "非洲" },
  { code: "244", zh: "坦尚尼亞", en: "Tanzania", continent: "非洲" },
  { code: "245", zh: "多哥", en: "Togo", continent: "非洲" },
  { code: "247", zh: "突尼西亞", en: "Tunisia", continent: "非洲" },
  { code: "248", zh: "烏干達", en: "Uganda", continent: "非洲" },
  { code: "250", zh: "剛果民主共和國", en: "Congo, Democratic Republic of the", continent: "非洲" },
  { code: "251", zh: "尚比亞", en: "Zambia", continent: "非洲" },
  { code: "253", zh: "辛巴威", en: "Zimbabwe", continent: "非洲" },
  { code: "255", zh: "布吉納法索", en: "Burkina Faso", continent: "非洲" },
  { code: "256", zh: "納米比亞", en: "Namibia", continent: "非洲" },
  { code: "257", zh: "厄利垂亞", en: "Eritrea", continent: "非洲" },
  { code: "258", zh: "南蘇丹共和國", en: "South Sudan", continent: "非洲" },
  { code: "259", zh: "索馬利蘭共和國", en: "Republic of Somaliland", continent: "非洲" },
  { code: "260", zh: "史瓦帝尼王國", en: "Kingdom of Eswatini", continent: "非洲" },
  { code: "301", zh: "阿爾巴尼亞", en: "Albania", continent: "歐洲" },
  { code: "302", zh: "安道爾", en: "Andorra", continent: "歐洲" },
  { code: "303", zh: "奧地利", en: "Austria", continent: "歐洲" },
  { code: "304", zh: "比利時", en: "Belgium", continent: "歐洲" },
  { code: "305", zh: "保加利亞", en: "Bulgaria", continent: "歐洲" },
  { code: "306", zh: "捷克", en: "Czech Republic", continent: "歐洲" },
  { code: "307", zh: "丹麥", en: "Denmark", continent: "歐洲" },
  { code: "309", zh: "芬蘭", en: "Finland", continent: "歐洲" },
  { code: "310", zh: "法國", en: "France", continent: "歐洲" },
  { code: "311", zh: "希臘", en: "Greece", continent: "歐洲" },
  { code: "312", zh: "教廷", en: "Holy See", continent: "歐洲" },
  { code: "313", zh: "匈牙利", en: "Hungary", continent: "歐洲" },
  { code: "314", zh: "冰島", en: "Iceland", continent: "歐洲" },
  { code: "315", zh: "愛爾蘭", en: "Ireland", continent: "歐洲" },
  { code: "316", zh: "義大利", en: "Italy", continent: "歐洲" },
  { code: "317", zh: "列支敦斯登", en: "Liechtenstein", continent: "歐洲" },
  { code: "318", zh: "盧森堡", en: "Luxembourg", continent: "歐洲" },
  { code: "319", zh: "馬爾他", en: "Malta", continent: "歐洲" },
  { code: "320", zh: "摩納哥", en: "Monaco", continent: "歐洲" },
  { code: "321", zh: "荷蘭", en: "Netherlands", continent: "歐洲" },
  { code: "322", zh: "挪威", en: "Norway", continent: "歐洲" },
  { code: "323", zh: "波蘭", en: "Poland", continent: "歐洲" },
  { code: "324", zh: "葡萄牙", en: "Portugal", continent: "歐洲" },
  { code: "325", zh: "羅馬尼亞", en: "Romania", continent: "歐洲" },
  { code: "326", zh: "聖馬利諾", en: "San Marino", continent: "歐洲" },
  { code: "327", zh: "西班牙", en: "Spain", continent: "歐洲" },
  { code: "328", zh: "瑞典", en: "Sweden", continent: "歐洲" },
  { code: "329", zh: "瑞士", en: "Switzerland", continent: "歐洲" },
  { code: "330", zh: "英國", en: "United Kingdom", continent: "歐洲" },
  { code: "332", zh: "德國", en: "Germany", continent: "歐洲" },
  { code: "334", zh: "克羅埃西亞", en: "Croatia", continent: "歐洲" },
  { code: "344", zh: "愛沙尼亞", en: "Estonia", continent: "歐洲" },
  { code: "348", zh: "拉脫維亞", en: "Latvia", continent: "歐洲" },
  { code: "349", zh: "立陶宛", en: "Lithuania", continent: "歐洲" },
  { code: "350", zh: "烏克蘭", en: "Ukraine", continent: "歐洲" },
  { code: "351", zh: "白俄羅斯", en: "Belarus", continent: "歐洲" },
  { code: "360", zh: "斯洛伐克", en: "Slovakia", continent: "歐洲" },
  { code: "361", zh: "斯洛維尼亞", en: "Slovenia", continent: "歐洲" },
  { code: "362", zh: "馬其頓", en: "Macedonia", continent: "歐洲" },
  { code: "363", zh: "塞爾維亞共和國", en: "Republic of Serbia", continent: "歐洲" },
  { code: "364", zh: "波士尼亞與赫塞哥維納", en: "Bosnia and Herzegovina", continent: "歐洲" },
  { code: "365", zh: "蒙特內哥羅", en: "Montenegro", continent: "歐洲" },
  { code: "366", zh: "科索沃共和國", en: "The Republic of Kosovo", continent: "歐洲" },
  { code: "367", zh: "北馬其頓共和國", en: "Republic of North Macedonia", continent: "歐洲" },
  { code: "401", zh: "巴哈馬", en: "Bahamas", continent: "北美洲" },
  { code: "402", zh: "巴貝多", en: "Barbados", continent: "北美洲" },
  { code: "403", zh: "加拿大", en: "Canada", continent: "北美洲" },
  { code: "404", zh: "哥斯大黎加", en: "Costa Rica", continent: "北美洲" },
  { code: "405", zh: "古巴", en: "Cuba", continent: "北美洲" },
  { code: "406", zh: "多明尼加", en: "Dominican Republic", continent: "北美洲" },
  { code: "407", zh: "薩爾瓦多", en: "El Salvador", continent: "北美洲" },
  { code: "408", zh: "格瑞那達", en: "Grenada", continent: "北美洲" },
  { code: "409", zh: "瓜地馬拉", en: "Guatemala", continent: "北美洲" },
  { code: "410", zh: "海地", en: "Haiti", continent: "北美洲" },
  { code: "411", zh: "宏都拉斯", en: "Honduras", continent: "北美洲" },
  { code: "412", zh: "牙買加", en: "Jamaica", continent: "北美洲" },
  { code: "413", zh: "墨西哥", en: "Mexico", continent: "北美洲" },
  { code: "414", zh: "尼加拉瓜", en: "Nicaragua", continent: "北美洲" },
  { code: "415", zh: "巴拿馬", en: "Panama", continent: "北美洲" },
  { code: "416", zh: "千里達", en: "Trinidad", continent: "北美洲" },
  { code: "418", zh: "貝里斯", en: "Belize", continent: "北美洲" },
  { code: "419", zh: "安地卡", en: "Antigua and Barbuda", continent: "北美洲" },
  { code: "420", zh: "聖文森", en: "St. Vincent & the Grenadines", continent: "北美洲" },
  { code: "423", zh: "波多黎各", en: "Puerto Rico", continent: "北美洲" },
  { code: "425", zh: "美國", en: "U.S.A.", continent: "北美洲" },
  { code: "426", zh: "多米尼克", en: "Dominica", continent: "北美洲" },
  { code: "427", zh: "聖露西亞", en: "St. Lucia", continent: "北美洲" },
  { code: "501", zh: "阿根廷", en: "Argentina", continent: "南美洲" },
  { code: "502", zh: "玻利維亞", en: "Bolivia", continent: "南美洲" },
  { code: "503", zh: "巴西", en: "Brazil", continent: "南美洲" },
  { code: "504", zh: "智利", en: "Chile", continent: "南美洲" },
  { code: "505", zh: "哥倫比亞", en: "Colombia", continent: "南美洲" },
  { code: "506", zh: "厄瓜多", en: "Ecuador", continent: "南美洲" },
  { code: "507", zh: "蓋亞那", en: "Guyana", continent: "南美洲" },
  { code: "508", zh: "巴拉圭", en: "Paraguay", continent: "南美洲" },
  { code: "509", zh: "秘魯", en: "Peru", continent: "南美洲" },
  { code: "510", zh: "蘇利南", en: "Suriname", continent: "南美洲" },
  { code: "511", zh: "烏拉圭", en: "Uruguay", continent: "南美洲" },
  { code: "512", zh: "委內瑞拉", en: "Venezuela", continent: "南美洲" },
  { code: "520", zh: "聖克里斯多福", en: "Saint Christopher and Nevis", continent: "南美洲" },
];

